[package]
org = "cosmobilis"
name = "check_disk_space"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "cosmobilis"
name = "job_patch"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "time"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "java_bindings"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "teams"
version = "0.1.0"
repository = "local"
